/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.DAO.KhoaHocDAO;
import com.edusys.DAO.ThongKeDAO;
import com.edusys.helper.Auth;
import com.edusys.helper.XImage;
import com.edusys.model.KhoaHoc;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tho
 */
public class ThongKeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeJFrame
     */
    public ThongKeJFrame(int index) {
        initComponents();
        tabs.setSelectedIndex(index);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnlNguoiHoc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();
        pnlBangDiem = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        pnlKhoaHoc = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKhoaHoc = new javax.swing.JTable();
        pnlDoanhThu = new javax.swing.JPanel();
        pnlTruongPhong = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        pnlNhanVien = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TỔNG HỢP THỐNG KÊ");

        pnlNguoiHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnlNguoiHoc.setLayout(new java.awt.BorderLayout());

        tblNguoiHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NĂM", "SỐ NGƯỜI HỌC", "ĐẦU TIÊN", "SAU CÙNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiHoc.setRowHeight(25);
        jScrollPane1.setViewportView(tblNguoiHoc);

        pnlNguoiHoc.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabs.addTab("NGƯỜI HỌC", new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/User group.png")), pnlNguoiHoc, "NGƯỜI HỌC"); // NOI18N

        pnlBangDiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnlBangDiem.setLayout(new java.awt.BorderLayout());

        tblBangDiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NH", "HỌ VÀ TÊN", "ĐIỂM", "XẾP LOẠI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangDiem.setRowHeight(25);
        jScrollPane2.setViewportView(tblBangDiem);

        pnlBangDiem.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("KHÓA HỌC: ");
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

        cboKhoaHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboKhoaHoc.setPreferredSize(new java.awt.Dimension(31, 32));
        cboKhoaHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKhoaHocItemStateChanged(evt);
            }
        });
        cboKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaHocActionPerformed(evt);
            }
        });
        cboKhoaHoc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboKhoaHocPropertyChange(evt);
            }
        });
        jPanel2.add(cboKhoaHoc, java.awt.BorderLayout.CENTER);

        pnlBangDiem.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tabs.addTab("BẢNG ĐIỂM", new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Numbered list.png")), pnlBangDiem, "BẢNG ĐIỂM"); // NOI18N

        pnlKhoaHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnlKhoaHoc.setLayout(new java.awt.BorderLayout());

        tblKhoaHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblKhoaHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CHUYÊN ĐỀ", "TỔNG SỐ HV", "THẤP NHẤT", "CAO NHẤT", "ĐIỂM TRUNG BÌNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoaHoc.setRowHeight(25);
        jScrollPane3.setViewportView(tblKhoaHoc);

        pnlKhoaHoc.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabs.addTab("TỔNG HỢP ĐIỂM", new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Clien list.png")), pnlKhoaHoc, "TỔNG HỢP ĐIỂM"); // NOI18N

        pnlDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnlDoanhThu.setLayout(new java.awt.CardLayout());

        pnlTruongPhong.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("NĂM: ");
        jPanel1.add(jLabel3, java.awt.BorderLayout.LINE_START);

        cboNam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboNam.setPreferredSize(new java.awt.Dimension(31, 32));
        cboNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNamItemStateChanged(evt);
            }
        });
        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });
        cboNam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboNamPropertyChange(evt);
            }
        });
        jPanel1.add(cboNam, java.awt.BorderLayout.CENTER);

        pnlTruongPhong.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CHUYÊN ĐỀ", "SỐ KHÓA", "SỐ HV", "DOANH THU", "HP CAO NHẤT", "HP THẤP NHẤT", "HP TRUNG BÌNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhThu.setRowHeight(30);
        jScrollPane4.setViewportView(tblDoanhThu);

        pnlTruongPhong.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pnlDoanhThu.add(pnlTruongPhong, "card1");

        pnlNhanVien.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setToolTipText("cẩn thận bị trừ lương");
        pnlNhanVien.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CHỈ TRƯỞNG PHÒNG MỚI ĐƯỢC XEM DOANH THU");
        jLabel5.setToolTipText("cẩn thận bị trừ lương");
        pnlNhanVien.add(jLabel5, java.awt.BorderLayout.CENTER);

        pnlDoanhThu.add(pnlNhanVien, "card2");

        tabs.addTab("DOANH THU", new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Coins.png")), pnlDoanhThu, "DOANH THU"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhoaHocItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhoaHocItemStateChanged

    private void cboKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaHocActionPerformed
fillTableBangDiem();        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhoaHocActionPerformed

    private void cboKhoaHocPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboKhoaHocPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhoaHocPropertyChange

    private void cboNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNamItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamItemStateChanged

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
fillTableDoanhThu();        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamActionPerformed

    private void cboNamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboNamPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fillComboBoxkhoaHoc();
        fillTableBangDiem();
        fillTableNguoiHoc();
        fillTablekhoaHoc();
        fillComboBoxNam();
        fillTableDoanhThu();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeJFrame(2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlBangDiem;
    private javax.swing.JPanel pnlDoanhThu;
    private javax.swing.JPanel pnlKhoaHoc;
    private javax.swing.JPanel pnlNguoiHoc;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlTruongPhong;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTable tblKhoaHoc;
    private javax.swing.JTable tblNguoiHoc;
    // End of variables declaration//GEN-END:variables
    KhoaHocDAO khdao = new KhoaHocDAO();
    ThongKeDAO dao = new ThongKeDAO();
    void init() {
        setIconImage(XImage.APP_ICON);
        CardLayout card= (CardLayout) pnlDoanhThu.getLayout();
        if(Auth.USER.isVaiTro()){
            card.show(pnlDoanhThu, "card1");
        }else{
            card.show(pnlDoanhThu, "card2");
        }
    }

    //xóa cbo, lấy tất cả đt KhoaHoc từ CSDL thêm mới vào cbo
    //chọn sẵn Item thứ nhất
    void fillComboBoxkhoaHoc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhoaHoc.getModel(); //kết nối cbo với model
        model.removeAllElements(); //xóa tất cả item
        List<KhoaHoc> list = khdao.selectAll();
        for (KhoaHoc kh : list) {
            model.addElement(kh);
        }
        cboKhoaHoc.setSelectedIndex(0);
    }
    

    //lấy tất cả năm của khóa học (int) điền vào cbo (điền đt int), ko điền trùng
    //chọn sẵn Item thứ nhất


    //xóa bảng điểm, điền dữ liệu vào bảng điểm theo MaKH
    void fillTableBangDiem() {
        DefaultTableModel model = (DefaultTableModel) tblBangDiem.getModel();
        model.setRowCount(0);     
         KhoaHoc kh = (KhoaHoc) cboKhoaHoc.getSelectedItem();
        List<Object[]> list = dao.getBangDiem(kh.getMaKH()); //lấy về 1 <Object[]> list theo MaKH
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    //xóa bảng người học, đièm dữ liệu vào bảng người học
    void fillTableNguoiHoc() {
        DefaultTableModel model = (DefaultTableModel) tblNguoiHoc.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao.getNguoiHoc();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    //xóa bảng tổng hợp điểm, điền dữ liệu vào bảng tổng hợp điểm
    void fillTablekhoaHoc() {
        DefaultTableModel model = (DefaultTableModel) tblKhoaHoc.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao.getDiemTheoChuyenDe();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    //xóa bảng doanh thu, điền dữ liệu vào bảng doanh thu theo năm tương ứng
    void fillTableDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        model.setRowCount(0);
        int nam = Integer.parseInt(cboNam.getSelectedItem().toString());
        List<Object[]> list = dao.getDoanhThu(nam);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
    void fillComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboNam.getModel();
        model.removeAllElements();
//        List<khoaHoc> list = khdao.select();
//        for (khoaHoc kh : list) {
//            int nam = kh.getNgayKG().getYear() + 1900; //date.getYear() trả về int năm của date - 1900
//            if (model.getIndexOf(nam) < 0) { //kiểm tra xem trong cbo đã có năm này chưa, nếu chưa có thì mới thêm năm
//                //model.getIndexOf(Object) trả về vị trí của object trong cbo, nêú chưa có trả về -1
//                model.addElement(nam);
//                //model.getElementAt(2);                  //chẳng để làm gì
//            }
//        }
        List<Integer> list=dao.getNamKhaiGiang();
        for(Integer nam: list){
            model.addElement(nam);
        }
        cboNam.setSelectedIndex(0);
    }
}
